apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - ingress.yaml

images:
   - name: ghcr.io/eknathdj/api
     newTag: latest
   - name: ghcr.io/eknathdj/web
     newTag: latest
